title: Lucia Gordon
description: PhD Student in Computer Science <br><a style="color:white;" href="http://www.linkedin.com/in/lucia-gordon-187069225">LinkedIn</a> | <a href="https://github.com/lgordon99">GitHub</a></br>
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
