remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Lucia Gordon
description: Hello! I’m Lucia, and I have been a PhD student in Computer Science at Harvard’s School for Engineering and Applied Sciences since Fall 2022. I work as a researcher in Milind Tambe’s Teamcore group. My undergraduate background is in physics and mathematics, but my graduate research interests lie in machine learning methods and applications to conservation, climate change, and sustainability. I’m currently working on the PAWS project to leverage AI in patrol planning to combat wildlife poaching.
